### ISSUE TITLE
Godot 3.1 Error

### ISSUE THREAD

**Issue by sbenson2** [qtip/tile-spawner#1]
Unable to load addon with godot 3.1. Resulting error pic attached. 
![Screenshot from 2019-03-24 11-54-57](https://user-images.githubusercontent.com/46143954/54884232-c825ee00-4e2b-11e9-9ab5-8d0c64d43a96.png)

**Comment by Animtim** [comment]
I found a fix and made a pull request.

**Comment by qtip** [comment]
Fixed by #2
